#!/usr/bin/env zsh

function build_alphabetical_processor(){

  echo "[+] Linkning and testing 6.2 ..........."
  clang src/*c vars_redo.c -o vars_6_2 && ./vars_6_2 tests/stdin_test.c 6

  rm vars_6_2
}

function build_cross_reference(){
  echo "[+] Linking and testing 6.3 ......."
  clang src/*c cross_reference_6_3.c -o cross_reference_6_3 && ./cross_reference_6_3 inputs/input
  rm cross_reference_6_3
}

function build_sorter(){
  echo "[+] Linking and testing 6.4 ......."
  clang src/*c sorter.c -o sorter && ./sorter inputs/harry_potter.txt
  rm sorter
}

function build_undef(){
  echo "[+] Linking and testing 6.5 ......."
  clang src/*c undef.c -o undef && ./undef inputs/dictionary
  rm undef
}

#build_alphabetical_processor
build_cross_reference
#build_sorter
#build_undef
