#!/usr/bin/env zsh

function succ_(){
  echo "[+] BUILD SUCCEEDED!"
  echo "[+] Number of non blank lines: $(cat ed_manip.c | sed '/^\s*#/d;/^\s*$/d' | wc -l)"
}

function err_(){
  echo "[-] BUILD FAILED"
  cat warning_error_logs.txt | less
  exit
}

function testing_with_files_(){

  echo "[+] Building from source...."

  #clang -lm -g "ed_manip.c" -o "ed_manip" 2> warning_error_logs.txt && succ_ || err_
  clang -lm -g "ed_manip.c" -o "ed_manip"

  cp "$target" ""$name"_cloned"
  target=""$name"_cloned"

  echo "[+] Contents of $target: "
  cat "$target"
  echo -e ",s/this/replaced/g\n,s/^yes/line/g\nw\nq" | ./ed_manip "$target"

  echo "[+] Contents of $target after replacement: "
  cat "$target"

  echo -e ",s/^line/LINE/g\nw\nq" | ./ed_manip "$target"
  echo "[+] Contents of $target after beginning line replacement:"
  cat "$target"

  rm "$target"
}

function testing_with_arguments_(){
  clang -lm -g "ed_manip.c" -o "ed_manip" 2> warning_error_logs.txt && succ_ || err_
  ./ed_manip -i "^EXPRESSION" ./input.txt
}

[[ -z "$@" ]] && exit
target="$1"
name="$1:t:r"
testing_with_arguments_
